# Ref: https://github.com/morrownr/rtw89/blob/main/dkms.conf
# Ref: https://manpages.ubuntu.com/manpages/jammy/man8/dkms.8.html
# General dkms approach: /usr/src/hiraid-2.1.0.1/
# Usually dkms.conf is clean with custom Makefile. This time Makefile remains original.
PACKAGE_NAME="hiraid"
PACKAGE_VERSION="2.1.0.1"
# BUILD_EXCLUSIVE_KERNEL="^(6\.[6-9]\.|6\.1[0-9]\.|7\.)"
AUTOINSTALL="yes"
MAKE="make -C $kernel_source_dir M=$source_tree/hiraid-2.1.0.1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules"
CLEAN="make -C $kernel_source_dir M=$source_tree/hiraid-2.1.0.1 clean"
BUILT_MODULE_NAME[0]="hiraid"
DEST_MODULE_LOCATION[0]="/updates/dkms/hiraid"
# DEST_MODULE_LOCATION[0]="/updates
